name: lazy_builder_widget
description: "A builder widget that can prevent rebuilding."
version: 0.0.1
homepage: https://github.com/XuanTung95/lazy_builder_widget.git

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
